import type { ProviderAdapter, ProviderSyncResult } from './provider.types';

function staticSync(result: ProviderSyncResult): ProviderAdapter['sync'] {
  return () => Promise.resolve(result);
}

export const providerAdapters: ProviderAdapter[] = [
  {
    provider: 'proxmox',
    displayName: 'Proxmox',
    syncIntervalSeconds: 60,
    credentials: [
      {
        key: 'baseUrl',
        label: 'Cluster API URL',
        envVar: 'PROXMOX_BASE_URL',
        sensitive: false,
      },
      {
        key: 'tokenId',
        label: 'API Token ID',
        envVar: 'PROXMOX_TOKEN_ID',
        sensitive: true,
      },
      {
        key: 'tokenSecret',
        label: 'API Token Secret',
        envVar: 'PROXMOX_TOKEN_SECRET',
        sensitive: true,
      },
    ],
    actions: [
      {
        id: 'proxmox.vm.power',
        label: 'VM Power Control',
        description: 'Reserved for Phase 6 start, stop, reboot, and shutdown.',
        supported: false,
      },
    ],
    sync: staticSync({
      status: 'healthy',
      headline: '2 nodes, 4 guests, quorum intact.',
      highlights: [
        'Cluster quorum healthy across both nodes.',
        'One container is running in warning posture pending agent reconnect.',
        'Backup coverage is visible for current guests.',
      ],
      assets: [
        {
          assetType: 'cluster',
          externalId: 'pve-cluster',
          name: 'Homelab Cluster',
          status: 'online',
          summary: 'Quorum stable and replication online.',
          metadata: { nodes: 2, guests: 4 },
        },
        {
          assetType: 'node',
          externalId: 'pve-01',
          name: 'pve-01',
          status: 'online',
          summary: 'CPU 38%, memory 62%, local storage 58% used.',
          metadata: { cpuPercent: 38, memoryPercent: 62, storagePercent: 58 },
        },
        {
          assetType: 'node',
          externalId: 'pve-02',
          name: 'pve-02',
          status: 'online',
          summary: 'CPU 24%, memory 48%, replication standby ready.',
          metadata: { cpuPercent: 24, memoryPercent: 48, storagePercent: 44 },
        },
        {
          assetType: 'vm',
          externalId: 'vm-120',
          name: 'plex-core',
          status: 'online',
          summary: 'Media VM online with guest agent responding.',
          metadata: { node: 'pve-01', powerState: 'running' },
        },
        {
          assetType: 'lxc',
          externalId: 'lxc-221',
          name: 'automation-edge',
          status: 'warning',
          summary: 'Guest agent reconnecting after routine package updates.',
          metadata: { node: 'pve-02', powerState: 'running' },
        },
      ],
      metrics: [
        {
          key: 'cluster.quorum',
          label: 'Cluster Quorum',
          valueText: 'Healthy',
          status: 'normal',
        },
        {
          key: 'node.cpu',
          label: 'Node CPU',
          unit: '%',
          valueText: '38%',
          valueNumber: 38,
          status: 'normal',
          assetRef: { assetType: 'node', externalId: 'pve-01' },
        },
        {
          key: 'node.cpu',
          label: 'Node CPU',
          unit: '%',
          valueText: '24%',
          valueNumber: 24,
          status: 'normal',
          assetRef: { assetType: 'node', externalId: 'pve-02' },
        },
        {
          key: 'guest.count',
          label: 'Running Guests',
          valueText: '4',
          valueNumber: 4,
          status: 'normal',
        },
      ],
    }),
  },
  {
    provider: 'truenas',
    displayName: 'TrueNAS',
    syncIntervalSeconds: 90,
    credentials: [
      {
        key: 'baseUrl',
        label: 'TrueNAS URL',
        envVar: 'TRUENAS_BASE_URL',
        sensitive: false,
      },
      {
        key: 'apiKey',
        label: 'API Key',
        envVar: 'TRUENAS_API_KEY',
        sensitive: true,
      },
    ],
    actions: [
      {
        id: 'truenas.pool.scrub',
        label: 'Pool Scrub Trigger',
        description: 'Reserved for later scrub and snapshot task actions.',
        supported: false,
      },
    ],
    sync: staticSync({
      status: 'degraded',
      headline: '2 pools visible, one disk showing elevated temperature.',
      highlights: [
        'Primary pool remains healthy with comfortable free space.',
        'Archive pool scrub completed successfully overnight.',
        'One SATA disk is in warning state due to temperature.',
      ],
      assets: [
        {
          assetType: 'pool',
          externalId: 'tank',
          name: 'tank',
          status: 'online',
          summary: 'Pool healthy with 41% free space remaining.',
          metadata: { capacityPercent: 59, health: 'ONLINE' },
        },
        {
          assetType: 'pool',
          externalId: 'archive',
          name: 'archive',
          status: 'online',
          summary: 'Archive pool healthy and scrubbed within the last 24 hours.',
          metadata: { capacityPercent: 68, health: 'ONLINE' },
        },
        {
          assetType: 'disk',
          externalId: 'ada0',
          name: 'WD Red 8TB',
          status: 'warning',
          summary: 'SMART healthy, but temperature is trending high at 46C.',
          metadata: { temperatureC: 46 },
        },
        {
          assetType: 'disk',
          externalId: 'ada1',
          name: 'Seagate IronWolf 8TB',
          status: 'online',
          summary: 'Normal temperature and no SMART alerts.',
          metadata: { temperatureC: 38 },
        },
      ],
      metrics: [
        {
          key: 'pool.capacity',
          label: 'Pool Capacity',
          unit: '%',
          valueText: '59%',
          valueNumber: 59,
          status: 'normal',
          assetRef: { assetType: 'pool', externalId: 'tank' },
        },
        {
          key: 'pool.capacity',
          label: 'Pool Capacity',
          unit: '%',
          valueText: '68%',
          valueNumber: 68,
          status: 'warning',
          assetRef: { assetType: 'pool', externalId: 'archive' },
        },
        {
          key: 'disk.temperature',
          label: 'Disk Temperature',
          unit: 'C',
          valueText: '46C',
          valueNumber: 46,
          status: 'warning',
          assetRef: { assetType: 'disk', externalId: 'ada0' },
        },
      ],
    }),
  },
  {
    provider: 'unifi',
    displayName: 'UniFi',
    syncIntervalSeconds: 45,
    credentials: [
      {
        key: 'baseUrl',
        label: 'Controller URL',
        envVar: 'UNIFI_BASE_URL',
        sensitive: false,
      },
      {
        key: 'username',
        label: 'Controller Username',
        envVar: 'UNIFI_USERNAME',
        sensitive: true,
      },
      {
        key: 'password',
        label: 'Controller Password',
        envVar: 'UNIFI_PASSWORD',
        sensitive: true,
      },
    ],
    actions: [
      {
        id: 'unifi.client.control',
        label: 'Client Control',
        description: 'Reserved for later reconnect and block workflows.',
        supported: false,
      },
    ],
    sync: staticSync({
      status: 'healthy',
      headline: 'Gateway, switch, and two APs online with stable WAN latency.',
      highlights: [
        'WAN latency steady at 11 ms.',
        '23 clients currently associated across the site.',
        'No rogue devices detected in the current snapshot.',
      ],
      assets: [
        {
          assetType: 'gateway',
          externalId: 'udm-se',
          name: 'UDM SE',
          status: 'online',
          summary: 'Gateway online and routing normally.',
          metadata: { latencyMs: 11, packetLossPercent: 0.2 },
        },
        {
          assetType: 'switch',
          externalId: 'usw-pro-24',
          name: 'USW Pro 24',
          status: 'online',
          summary: 'All core uplinks healthy and PoE budget within range.',
          metadata: { activePorts: 14 },
        },
        {
          assetType: 'access-point',
          externalId: 'u6-lr-lounge',
          name: 'U6 LR Lounge',
          status: 'online',
          summary: 'Strong Wi-Fi performance and healthy client load.',
          metadata: { clients: 11 },
        },
        {
          assetType: 'access-point',
          externalId: 'u6-mesh-office',
          name: 'U6 Mesh Office',
          status: 'online',
          summary: 'Backhaul healthy and low retry rates.',
          metadata: { clients: 12 },
        },
      ],
      metrics: [
        {
          key: 'wan.latency',
          label: 'WAN Latency',
          unit: 'ms',
          valueText: '11 ms',
          valueNumber: 11,
          status: 'normal',
          assetRef: { assetType: 'gateway', externalId: 'udm-se' },
        },
        {
          key: 'wan.packet-loss',
          label: 'Packet Loss',
          unit: '%',
          valueText: '0.2%',
          valueNumber: 0.2,
          status: 'normal',
          assetRef: { assetType: 'gateway', externalId: 'udm-se' },
        },
        {
          key: 'clients.connected',
          label: 'Connected Clients',
          valueText: '23',
          valueNumber: 23,
          status: 'normal',
        },
      ],
    }),
  },
  {
    provider: 'home-assistant',
    displayName: 'Home Assistant',
    syncIntervalSeconds: 30,
    credentials: [
      {
        key: 'baseUrl',
        label: 'Home Assistant URL',
        envVar: 'HOME_ASSISTANT_BASE_URL',
        sensitive: false,
      },
      {
        key: 'accessToken',
        label: 'Long-Lived Access Token',
        envVar: 'HOME_ASSISTANT_ACCESS_TOKEN',
        sensitive: true,
      },
    ],
    actions: [
      {
        id: 'home-assistant.entity.toggle',
        label: 'Entity Toggle',
        description: 'Reserved for Phase 6 automation, scene, and toggle actions.',
        supported: false,
      },
    ],
    sync: staticSync({
      status: 'healthy',
      headline: '28 entities and 6 automations are available for read-only monitoring.',
      highlights: [
        'Entry, garage, and office device groups all report online.',
        'Automations have completed their last run without errors.',
        'Energy readings are flowing for the current day.',
      ],
      assets: [
        {
          assetType: 'entity',
          externalId: 'sensor.office_temperature',
          name: 'Office Temperature',
          status: 'online',
          summary: 'Current office reading is 72F.',
          metadata: { state: '72', unit: 'F' },
        },
        {
          assetType: 'entity',
          externalId: 'binary_sensor.front_door',
          name: 'Front Door Sensor',
          status: 'online',
          summary: 'Door is closed and sensor is available.',
          metadata: { state: 'off' },
        },
        {
          assetType: 'automation',
          externalId: 'automation.evening_scene',
          name: 'Evening Scene',
          status: 'online',
          summary: 'Automation enabled and last triggered successfully.',
          metadata: { enabled: true },
        },
        {
          assetType: 'automation',
          externalId: 'automation.night_lock_check',
          name: 'Night Lock Check',
          status: 'online',
          summary: 'Automation enabled and awaiting next scheduled window.',
          metadata: { enabled: true },
        },
      ],
      metrics: [
        {
          key: 'entity.count',
          label: 'Available Entities',
          valueText: '28',
          valueNumber: 28,
          status: 'normal',
        },
        {
          key: 'automation.enabled',
          label: 'Enabled Automations',
          valueText: '6',
          valueNumber: 6,
          status: 'normal',
        },
        {
          key: 'energy.today',
          label: 'Energy Today',
          unit: 'kWh',
          valueText: '18.4 kWh',
          valueNumber: 18.4,
          status: 'normal',
        },
      ],
    }),
  },
  {
    provider: 'plex',
    displayName: 'Plex',
    syncIntervalSeconds: 60,
    credentials: [
      {
        key: 'baseUrl',
        label: 'Plex Server URL',
        envVar: 'PLEX_BASE_URL',
        sensitive: false,
      },
      {
        key: 'token',
        label: 'Plex Token',
        envVar: 'PLEX_TOKEN',
        sensitive: true,
      },
    ],
    actions: [
      {
        id: 'plex.library.scan',
        label: 'Library Scan',
        description: 'Reserved for later library scan and supported playback actions.',
        supported: false,
      },
    ],
    sync: staticSync({
      status: 'degraded',
      headline: 'Server reachable with 2 active streams and one transcode in flight.',
      highlights: [
        'Movie and TV libraries both remain reachable.',
        'One stream is currently transcoding and pushing CPU higher than ideal.',
        'Recently added items were indexed within the last hour.',
      ],
      assets: [
        {
          assetType: 'server',
          externalId: 'plex-main',
          name: 'Plex Main',
          status: 'warning',
          summary: 'Server online with elevated transcode activity.',
          metadata: { activeStreams: 2, transcodes: 1 },
        },
        {
          assetType: 'library',
          externalId: 'library-movies',
          name: 'Movies',
          status: 'online',
          summary: '1,284 titles indexed and healthy.',
          metadata: { items: 1284 },
        },
        {
          assetType: 'library',
          externalId: 'library-tv',
          name: 'TV Shows',
          status: 'online',
          summary: '312 series indexed and scan queue clear.',
          metadata: { items: 312 },
        },
        {
          assetType: 'session',
          externalId: 'session-1001',
          name: 'Living Room Stream',
          status: 'online',
          summary: 'Direct play session active in the living room.',
          metadata: { mode: 'direct-play' },
        },
        {
          assetType: 'session',
          externalId: 'session-1002',
          name: 'Tablet Stream',
          status: 'warning',
          summary: 'Remote stream is transcoding to a lower bitrate.',
          metadata: { mode: 'transcode' },
        },
      ],
      metrics: [
        {
          key: 'streams.active',
          label: 'Active Streams',
          valueText: '2',
          valueNumber: 2,
          status: 'normal',
          assetRef: { assetType: 'server', externalId: 'plex-main' },
        },
        {
          key: 'streams.transcode',
          label: 'Transcodes',
          valueText: '1',
          valueNumber: 1,
          status: 'warning',
          assetRef: { assetType: 'server', externalId: 'plex-main' },
        },
        {
          key: 'bandwidth.current',
          label: 'Bandwidth',
          unit: 'Mbps',
          valueText: '28 Mbps',
          valueNumber: 28,
          status: 'normal',
        },
      ],
    }),
  },
  {
    provider: 'github',
    displayName: 'GitHub',
    syncIntervalSeconds: 120,
    credentials: [
      {
        key: 'apiUrl',
        label: 'GitHub API URL',
        envVar: 'GITHUB_API_URL',
        sensitive: false,
      },
      {
        key: 'token',
        label: 'Personal Access Token',
        envVar: 'GITHUB_TOKEN',
        sensitive: true,
      },
    ],
    actions: [
      {
        id: 'github.workflow.dispatch',
        label: 'Workflow Dispatch',
        description: 'Reserved for Phase 6 workflow dispatch and rerun actions.',
        supported: false,
      },
    ],
    sync: staticSync({
      status: 'healthy',
      headline: '3 repositories monitored with 5 recent workflow runs and 2 open pull requests.',
      highlights: [
        'Main branch protections remain green across the tracked repositories.',
        'One workflow run failed in the last hour and is surfaced for follow-up.',
        'Two pull requests are awaiting review decisions.',
      ],
      assets: [
        {
          assetType: 'repository',
          externalId: 'nexus',
          name: 'nexus',
          status: 'online',
          summary: 'Repository healthy with active Actions workflows.',
          metadata: { defaultBranch: 'main' },
        },
        {
          assetType: 'workflow',
          externalId: 'nexus-ci',
          name: 'CI',
          status: 'warning',
          summary: 'One recent run failed on tests and awaits rerun.',
          metadata: { recentFailures: 1 },
        },
        {
          assetType: 'workflow',
          externalId: 'nexus-release',
          name: 'Release',
          status: 'online',
          summary: 'Release workflow is idle and ready.',
          metadata: { recentFailures: 0 },
        },
        {
          assetType: 'pull-request',
          externalId: 'pr-182',
          name: 'Phase 2 integration framework',
          status: 'online',
          summary: 'Checks passing and awaiting review.',
          metadata: { checks: 'passing' },
        },
        {
          assetType: 'pull-request',
          externalId: 'pr-183',
          name: 'Alert routing follow-up',
          status: 'warning',
          summary: 'Awaiting one required status check.',
          metadata: { checks: 'pending' },
        },
      ],
      metrics: [
        {
          key: 'workflow.runs',
          label: 'Recent Workflow Runs',
          valueText: '5',
          valueNumber: 5,
          status: 'normal',
        },
        {
          key: 'workflow.failures',
          label: 'Failed Jobs',
          valueText: '1',
          valueNumber: 1,
          status: 'warning',
        },
        {
          key: 'pull-requests.open',
          label: 'Open Pull Requests',
          valueText: '2',
          valueNumber: 2,
          status: 'normal',
        },
      ],
    }),
  },
];
